### PR TITLE
Support repeated and map fields in field_mask

### LINKED ISSUE #1: Generation for repeated fields and map fields fails
FieldMask documentation says that repeated fields (and map field) are supported only if they are in the last position of a field mask. Field mask generation currently does not take that into account and fails. Example of failing proto file:

```protobuf
syntax = "proto3";

import "google/protobuf/field_mask.proto";
import "fieldmask/option.proto";

message UserInfoRequest {
  string user_id = 1;
  google.protobuf.FieldMask field_mask = 2 [
    (fieldmask.option.Option).in = {gen: true},
    (fieldmask.option.Option).out = {gen: true, message:"UserInfoResponse"}
  ];
}

message Address {
  string country = 1;
  string province = 2;
}

message UserInfoResponse {
  string user_id = 1;
  string name = 2;
  string email = 3;
  repeated Address addresses = 4;
}
```

### PR DESCRIPTION
**Pull request by vaidasn**
Fixes #1

### CODE REVIEW

**Comment by yeqown** [comment]
changes could not support repeated fields

**Comment by vaidasn** [comment]
This PR works correctly for my project which has repeated field.

**Comment by yeqown** [comment]
What result did you get? The changes just want skip the case, how does it support `repeated` fields?

**Comment by vaidasn** [comment]
The template is also called recursively from message.tpl#L43. As https://pkg.go.dev/github.com/lyft/protoc-gen-star#FieldType states `$f.Type.Embed` returns `nil` for maps and repeated fields.

**Comment by yeqown** [comment]
I know that, what I really mean is that you'r purpose is fixing it rather than supporting it. Acutally, in my thought the repeated field should be treated as embed field to generate if it is a message type.

**Pull request merged**
