### PR TITLE
Allow one of .in or .out option to be skipped

### LINKED ISSUE #3: Both .in or .out options have to be specified for field_mask field
In case only one of .in or .out options is specified for a `FieldMask` field the generation fails. Example of failing proto file:

```protobuf
syntax = "proto3";

import "google/protobuf/field_mask.proto";
import "fieldmask/option.proto";

message UserInfoRequest {
  string user_id = 1;
  google.protobuf.FieldMask field_mask = 2 [
    (fieldmask.option.Option).out = {gen: true, message:"UserInfoResponse"}
  ];
}

message Address {
  string country = 1;
  string province = 2;
}

message UserInfoResponse {
  string user_id = 1;
  string name = 2;
  string email = 3;
  Address address = 4;
}
```

### PR DESCRIPTION
**Pull request by vaidasn**
Fixes #3

### CODE REVIEW

**Comment by yeqown** [comment]
modify `fm_message_in.go#L45` maybe better, construct `opt(pbfieldmask.FieldMask)` to make sure `In` and `Out` has been initialized.

```go
		opt := &pbfieldmask.FieldMask{
			In:  new(pbfieldmask.InMessageOption),
			Out: new(pbfieldmask.OutMessageOption),
		}
```

**Comment by vaidasn** [comment]
> modify `fm_message_in.go#L45` maybe better, construct `opt(pbfieldmask.FieldMask)` to make sure `In` and `Out` has been initialized.
> 
> ```go
> 		opt := &pbfieldmask.FieldMask{
> 			In:  new(pbfieldmask.InMessageOption),
> 			Out: new(pbfieldmask.OutMessageOption),
> 		}
> ```

Your proposed fix doesn’t help, I’m still getting the error:

```[error] unable to convert user.pb.fm.go to proto: template: go:12:22: executing "go" at <$pair.FieldMaskOption.In.Gen>: nil pointer evaluating *fieldmask.InMessageOption.Gen```

However there is no error with my PR.

**Comment by yeqown** [comment]
fine, give me try

**Comment by yeqown** [comment]
I see, 
```go
ok, err := f.Extension(pbfieldmask.E_Option, &opt)
```
This function would overwrite `opt`, so the initialization would lose efficacy.

**Pull request merged**
